### ISSUE TITLE
I can't open project in android studio preview 3.0 preview

### ISSUE THREAD

**Issue by rooest** [EfeBudak/popular-movies-with-dagger#1]
Error....../secret.properties (No such file or directory)
Consult IDE log for more details (Help | Show Log)

**Comment by EfeBudak** [comment]
I have added information about secret.properties on README file. You need to get your own API key from [this](https://www.themoviedb.org/settings/api) link. 

That should solve the problem.

**Comment by rooest** [comment]
Thanks. It solved
